version = 0.1
[default.deploy.parameters]
stack_name = "no-as-a-service"
resolve_s3 = true
s3_prefix = "no-as-a-service"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
